

import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class Interface extends javax.swing.JFrame {
    private SingleListContainer <Foto> c = new SingleListContainer<>();
    private String id;
    private String loggedId;
    private String loggedPsw;
    private String psw;
    private String foto;
    private String list;
    private Iterator<Foto> it;
    private DefaultListModel <String> listUser = new DefaultListModel <> () ;

    private void foo() throws UserNotInException {
        it = c.getIterator(loggedId, loggedPsw);
        list = "";
        while (it.hasNext()) {
            list = list + it.next().toString() + ", ";
        }
        jTextArea_list.setText(list);
        jTextArea_registeredUser.setText(c.toString());
    }

    /**
     * Creates new form NewJFrame
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel_iscrizione = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_op = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        put = new javax.swing.JButton();
        get = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        copy = new javax.swing.JButton();
        share = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jText_foto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_list = new javax.swing.JTextArea();
        jLabel_userLogged = new javax.swing.JLabel();
        jTextField_share = new javax.swing.JTextField();
        panel_credenziali = new javax.swing.JPanel();
        b_iscriviti = new javax.swing.JButton();
        TextField_username = new javax.swing.JTextField();
        TextField_password = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel_registeredUsers = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_registeredUser = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Container");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Container");

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        jTextField1.setText("");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("id:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("password:");

        jTextField2.setText("");

        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_iscrizione.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_iscrizione.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_iscrizione.setText("Non registrato? Iscriviti!");
        jLabel_iscrizione.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_iscrizioneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_iscrizioneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_iscrizioneMouseExited(evt);
            }
        });

        jPanel_op.setVisible(false);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Utente loggato:");

        put.setBackground(new java.awt.Color(0, 153, 0));
        put.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        put.setForeground(new java.awt.Color(0, 0, 0));
        put.setText("put");
        put.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                putMouseClicked(evt);
            }
        });
        put.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                putActionPerformed(evt);
            }
        });

        get.setBackground(new java.awt.Color(0, 153, 0));
        get.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        get.setForeground(new java.awt.Color(0, 0, 0));
        get.setText("get");
        get.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getMouseClicked(evt);
            }
        });

        remove.setBackground(new java.awt.Color(0, 153, 0));
        remove.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        remove.setForeground(new java.awt.Color(0, 0, 0));
        remove.setText("remove");
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });

        copy.setBackground(new java.awt.Color(0, 153, 0));
        copy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        copy.setForeground(new java.awt.Color(0, 0, 0));
        copy.setText("copy");
        copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copyMouseClicked(evt);
            }
        });

        share.setBackground(new java.awt.Color(0, 153, 0));
        share.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        share.setForeground(new java.awt.Color(0, 0, 0));
        share.setText("share");
        share.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shareMouseClicked(evt);
            }
        });
        share.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Inserire dato:");

        jText_foto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jText_foto.setText("");

        jTextArea_list.setColumns(20);
        jTextArea_list.setRows(5);
        jScrollPane2.setViewportView(jTextArea_list);

        jLabel_userLogged.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel_userLogged.setText("jLabel4");

        jTextField_share.setText("Other");
        jTextField_share.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_shareMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_opLayout = new javax.swing.GroupLayout(jPanel_op);
        jPanel_op.setLayout(jPanel_opLayout);
        jPanel_opLayout.setHorizontalGroup(
            jPanel_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_opLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_opLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_userLogged))
                    .addGroup(jPanel_opLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_opLayout.createSequentialGroup()
                        .addComponent(put, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(get, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(copy, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(share, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_share, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel_opLayout.setVerticalGroup(
            jPanel_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_opLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(put)
                    .addComponent(get)
                    .addComponent(remove)
                    .addComponent(copy)
                    .addComponent(share)
                    .addComponent(jLabel_userLogged)
                    .addComponent(jTextField_share, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_opLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jText_foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panel_credenziali.setVisible(false);

        b_iscriviti.setBackground(new java.awt.Color(0, 102, 0));
        b_iscriviti.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        b_iscriviti.setText("Iscriviti");
        b_iscriviti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_iscrivitiMouseClicked(evt);
            }
        });

        TextField_username.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextField_username.setText("Username");
        TextField_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextField_usernameMouseClicked(evt);
            }
        });

        TextField_password.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TextField_password.setText("Password");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Iscriviti");

        javax.swing.GroupLayout panel_credenzialiLayout = new javax.swing.GroupLayout(panel_credenziali);
        panel_credenziali.setLayout(panel_credenzialiLayout);
        panel_credenzialiLayout.setHorizontalGroup(
            panel_credenzialiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_credenzialiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_credenzialiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panel_credenzialiLayout.createSequentialGroup()
                        .addComponent(TextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(TextField_password))
                    .addComponent(b_iscriviti, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
            .addGroup(panel_credenzialiLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_credenzialiLayout.setVerticalGroup(
            panel_credenzialiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_credenzialiLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_credenzialiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(b_iscriviti, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_registeredUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Elementi Container", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 1, 18))); // NOI18N
        jPanel_registeredUsers.setVisible(false);

        jTextArea_registeredUser.setColumns(20);
        jTextArea_registeredUser.setRows(5);
        jScrollPane1.setViewportView(jTextArea_registeredUser);

        javax.swing.GroupLayout jPanel_registeredUsersLayout = new javax.swing.GroupLayout(jPanel_registeredUsers);
        jPanel_registeredUsers.setLayout(jPanel_registeredUsersLayout);
        jPanel_registeredUsersLayout.setHorizontalGroup(
            jPanel_registeredUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registeredUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_registeredUsersLayout.setVerticalGroup(
            jPanel_registeredUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
        );


        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel_registeredUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_credenziali, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panel_credenziali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_registeredUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_op, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(585, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addComponent(jLabel_iscrizione, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(118, 118, 118))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_iscrizione)
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    //controllare che ci sia <id, pasw>
    try {
        String s = c.usersToString();
        if (s.contains(jTextField1.getText() + ", " + jTextField2.getText())) {
            loggedId = jTextField1.getText();
            loggedPsw = jTextField2.getText();
            JOptionPane.showMessageDialog(null, "Credenziali corrette!", "yy", 1);
            jPanel_op.setVisible(true);
            jLabel_userLogged.setText(loggedId);
            jTextField1.setText("");
            jTextField2.setText("");
            jText_foto.setText("");
            jTextField_share.setText("Other");
            foo();
        } else {
            throw new IllegalArgumentException();
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "Utente non registrato",  ex.toString() , 2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel_iscrizioneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_iscrizioneMouseClicked
        panel_credenziali.setVisible(true);

    }//GEN-LAST:event_jLabel_iscrizioneMouseClicked

    private void shareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shareActionPerformed

    private void putActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_putActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_putActionPerformed

    private void jLabel_iscrizioneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_iscrizioneMouseEntered
        jLabel_iscrizione.setText(("<HTML><U>Non registrato? Iscriviti!</U></HTML>"));
    }//GEN-LAST:event_jLabel_iscrizioneMouseEntered

    private void jLabel_iscrizioneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_iscrizioneMouseExited
        jLabel_iscrizione.setText("Non registrato? Iscriviti!");
    }//GEN-LAST:event_jLabel_iscrizioneMouseExited

    private void TextField_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextField_usernameMouseClicked
        TextField_username.setText(""); //crea user
        TextField_password.setText("");
    }//GEN-LAST:event_TextField_usernameMouseClicked

    private void b_iscrivitiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_iscrivitiMouseClicked
        id = TextField_username.getText();
        psw = TextField_password.getText();
        try {
            c.createUser(id, psw);
            TextField_username.setText("");
            TextField_password.setText("");
            JOptionPane.showMessageDialog(null, "Utente aggiunto", "Container", 1);
            TextField_username.setText("Username");
            TextField_password.setText("Password");
            jPanel_registeredUsers.setVisible(true);
            jTextArea_registeredUser.setText(c.toString());

        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Utente già registrato", e.toString()  , 2);

        }

    }//GEN-LAST:event_b_iscrivitiMouseClicked

    private void putMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_putMouseClicked
        try {
            Foto f = new Foto (jText_foto.getText());
            c.put(loggedId, loggedPsw, f);
            JOptionPane.showMessageDialog(null, f.toString() + " aggiunta!", "Container", 1);
            foo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), e.toString(), 2);
        }
    }//GEN-LAST:event_putMouseClicked

    private void getMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getMouseClicked
        try {
            Foto f = new Foto (jText_foto.getText());
            c.get(loggedId, loggedPsw, f);
            JOptionPane.showMessageDialog(null, f.toString() + " scaricata!", "Container", 1);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), e.toString(), 2);
        }
    }//GEN-LAST:event_getMouseClicked

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        try {
            Foto f = new Foto (jText_foto.getText());
            c.remove(loggedId, loggedPsw, f);
            JOptionPane.showMessageDialog(null, f.toString() + " rimosse!", "Container", 1);
            foo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), e.toString(), 2);
        }
    }//GEN-LAST:event_removeMouseClicked

    private void copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copyMouseClicked
        try {
            Foto f = new Foto (jText_foto.getText());
            c.copy(loggedId, loggedPsw, f);
            JOptionPane.showMessageDialog(null, f.toString() + " copiata!", "Container", 1);
            foo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), e.toString(), 2);
        }
    }//GEN-LAST:event_copyMouseClicked

    private void shareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shareMouseClicked
        try {
            String other = jTextField_share.getText();
            if (other.equals(loggedId)) {
                JOptionPane.showMessageDialog(null, "...", "...", 2);
                return;
            }
            Foto f = new Foto (jText_foto.getText());
            c.share(loggedId, loggedPsw, other, f);
            JOptionPane.showMessageDialog(null, f.toString() + " Condivisa!", "Container", 1);
            foo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString(), e.toString(), 2);
        }
    }//GEN-LAST:event_shareMouseClicked

    private void jTextField_shareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_shareMouseClicked
        jTextField_share.setText("");
    }//GEN-LAST:event_jTextField_shareMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextField_password;
    private javax.swing.JTextField TextField_username;
    private javax.swing.JButton b_iscriviti;
    private javax.swing.JButton copy;
    private javax.swing.JButton get;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_iscrizione;
    private javax.swing.JLabel jLabel_userLogged;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_op;
    private javax.swing.JPanel jPanel_registeredUsers;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_list;
    private javax.swing.JTextArea jTextArea_registeredUser;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_share;
    private javax.swing.JTextField jText_foto;
    private javax.swing.JPanel panel_credenziali;
    private javax.swing.JButton put;
    private javax.swing.JButton remove;
    private javax.swing.JButton share;
    // End of variables declaration//GEN-END:variables
}
